name: Hugo Build and Cache

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: .hugo_cache
          key: ${{ runner.os }}-hugo-${{ hashFiles('hugo.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --cacheDir "./.hugo_cache"

      - name: Cache Save
        id: cache-save
        if: success()
        uses: actions/cache/save@v4
        with:
          path: .hugo_cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
